project/pages/urls.py
from django.urls import path, include
from . import views

app_name = 'pages'

urlpatterns = [
    path('', views.home_page, name='home_page'),
]

project/project/urls.py
from django.conf.urls.static import static
from django.conf import settings
import os

from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pages.urls', namespace='pages')),
    path('recipe/', include('recipe.urls', namespace='recipe')),
    path('users/', include('users.urls', namespace='user')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
else:
    from django.views.static import serve
    from django.urls import re_path

    urlpatterns += [
        re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    ]

project/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    {% block head %} {% endblock %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
    <title>{% block title %} {% endblock %}</title>
</head>
<body>
    {% block content %}

    {% endblock %}
</body>

</html>

project/templates/footer.html
<footer class="mt-5 mt-auto w-100">
    <div class="container-footer bg-light w-100 d-flex justify-content-between align-items-center p-2">
        <span class="ms-5">©Aresta Simone</span>
        <a href="/admin" class="text-muted">Admin</a>
    </div>
</footer>

<style>
    html, body {
        height: 100%;
    }

    body {
        display: flex;
        flex-direction: column;
    }

    .container-footer {
        flex: 1;
        width: 100%;
        margin-top: 20px;
    }
</style>

project/templates/head.html
{% load static %}

<div class="d-flex justify-content-center py-2 bg-light">
    <!-- Logo Section -->
    <div class="logo">
        <a href="{% url 'pages:home_page' %}">
            <img src="{% static 'imgs/logo.png' %}" alt="Logo" width="150" height="120">
        </a>
    </div>
</div>