project/pages/urls.py
from django.urls import path, include
from . import views

app_name = 'pages'

urlpatterns = [
    path('', views.home_page, name='home_page'),
]

project/project/urls.py
from django.conf.urls.static import static
from django.conf import settings
import os

from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pages.urls', namespace='pages')),
    path('recipe/', include('recipe.urls', namespace='recipe')),
    path('users/', include('users.urls', namespace='user')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
else:
    from django.views.static import serve
    from django.urls import re_path

    urlpatterns += [
        re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    ]

project/recipe/urls.py
from django.urls import path
from .views import *

app_name = 'recipe'

urlpatterns = [
    path('createRecipe/', RecipeCreateView.as_view(), name='create_recipe'),
    path('createIngredient/', IngredientCreateView.as_view(), name='create_ingredient'),
    path('createBulkIngredient/', BulkIngredientCreateView.as_view(), name='create_bulk_ingredient'),
    path('deleteRecipe/<int:pk>/', RecipeDeleteView.as_view(), name='delete_recipe'),
    path('updateRecipe/<int:pk>/', RecipeUpdateView.as_view(), name='update_recipe'),
    path('listIngredients/', IngredientListView.as_view(), name='list_ingredients'),
    path('updateIngredient/<int:pk>/', update_ingredient, name='update_ingredient'),
    path('deleteIngredient/<int:pk>/', delete_ingredient, name='delete_ingredient'),
    path('createCategory/', CategoryCreateView.as_view(), name='create_category'),
    path('listCategories/', CategoryListView.as_view(), name='list_categories'),
    path('updateCategory/<int:pk>/', update_category, name='update_category'),
    path('deleteCategory/<int:pk>/', delete_category, name='delete_category'),
    path('detailRecipe/<int:pk>/', RecipeDetailView.as_view(), name='detail_recipe'),

]

project/users/urls.py
from django.urls import path
from .views import *
from django.contrib.auth import views as auth_views

app_name = 'users'

urlpatterns = [
    path("register/", UserCreateView.as_view(), name="register"),
    path("login/", auth_views.LoginView.as_view(), name="login"),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
]

project/pages/templates/pages/home_page.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Home page{% endblock %}

{% block head %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.min.js"></script>
{% endblock %}

{% block content %}
    {% if user.is_authenticated %}
        {% block navbar %}
            <!-- Navbar -->
            <nav class="navbar navbar-expand-lg navbar-light bg-light">
                <div class="container-fluid">
                    <!-- Navbar buttons -->
                    <ul class="navbar-nav">
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="recipesDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Ricette
                            </a>
                            <ul class="dropdown-menu" aria-labelledby="recipesDropdown">
                                <li><a class="dropdown-item" href="{% url 'recipe:create_recipe' %}">Aggiungi</a></li>
                            </ul>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="ingredientsDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Ingredienti
                            </a>
                            <ul class="dropdown-menu" aria-labelledby="ingredientsDropdown">
                                <li><a class="dropdown-item" href="{% url 'recipe:create_ingredient' %}">Aggiungi</a></li>
                                <li><a class="dropdown-item" href="{% url 'recipe:list_ingredients' %}">Lista</a></li>
                            </ul>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="categoriesDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Categorie
                            </a>
                            <ul class="dropdown-menu" aria-labelledby="categoriesDropdown">
                                <li><a class="dropdown-item" href="{% url 'recipe:create_category' %}">Aggiungi</a></li>
                                <li><a class="dropdown-item" href="{% url 'recipe:list_categories' %}">Lista</a></li>
                            </ul>
                        </li>
                    </ul>
                    <ul class="navbar-nav ms-auto">
                        <li class="nav-item">
                            <form action="{% url 'users:logout' %}" method="post" style="display: inline;">
                                {% csrf_token %}
                                <button type="submit" class="btn btn-dark">Logout</button>
                            </form>
                        </li>
                    </ul>

                </div>
            </nav>
        {% endblock %}

        <h1 class="text-center">Welcome {{ user }} to recipe book</h1>
        <div class="container mt-3">
            <h3>Filtri</h3>
            <div class="row g-3 align-items-center">
                <!-- Filtro per Categoria -->
                <div class="col-md-4">
                    <label for="categoryFilter" class="form-label">Categoria</label>
                    <select id="categoryFilter" class="form-select">
                        <option value="">Tutte le categorie</option>
                        {% for cat in categories %}
                            <option value="{{ cat.name }}">{{ cat.name }}</option>
                        {% endfor %}
                    </select>
                </div>
                <!-- Filtro per Ingredienti tramite SELECT -->
                <div class="col-md-8">
                    <label for="ingredientSelect" class="form-label">Ingredienti</label>
                    <select id="ingredientSelect" class="form-select">
                        <option value="">Seleziona un ingrediente</option>
                        {% for ing in ingredients %}
                            <option value="{{ ing.name }}">{{ ing.name }}</option>
                        {% endfor %}
                    </select>
                    <!-- Container per mostrare gli ingredienti selezionati -->
                    <div id="selectedIngredients" class="mt-2"></div>
                </div>
            </div>
        </div>

        <!-- Barra di ricerca -->
        <div class="container text-center mt-5">
            <label for="searchInput" class="h4 form-label">Cerca ricette</label>
            <input class="form-control rounded-pill mx-auto mb-4" id="searchInput" style="width: 50%; height: 50px;" type="search" placeholder="Cerca ricette" aria-label="Search">

            <!-- Lista delle ricette -->
            {% for recipe in recipes %}
                <div class="d-flex justify-content-center mb-3 recipe-container"
                     data-category="{{ recipe.category.name }}"
                     data-ingredients="{% for ri in recipe.ingredients.all %}{{ ri.ingredient.name }}{% if not forloop.last %}, {% endif %}{% endfor %}">
                    <div class="card my-2 rounded" onclick="window.location.href='{% url 'recipe:detail_recipe' recipe.pk %}'" style="flex:0.35;">
                        <div class="row g-0">
                            <div class="col-md-4 image-container">
                                <img src="{{ recipe.image.url }}" class="img-fluid rounded-start" alt="img" style="object-fit: contain; max-height: 70px">
                            </div>
                            <div class="col-md-8">
                                <div class="card-body">
                                    <h5 class="card-title">{{ recipe.name }}</h5>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="d-flex flex-column justify-content-center ms-2">
                        <a href="{% url 'recipe:delete_recipe' recipe.pk %}" class="btn btn-outline-danger btn-sm mb-2">
                            <i class="fas fa-trash-alt"></i>
                        </a>
                        <a href="{% url 'recipe:update_recipe' recipe.pk %}" class="btn btn-outline-primary btn-sm">
                            <i class="fas fa-cogs"></i>
                        </a>
                    </div>
                </div>
            {% endfor %}
        </div>
    {% else %}
        {% include 'head.html' %}
        <h1 class="text-center">Welcome to recipe book</h1>
        <div class="container mt-3 text-center">
            <a class="btn btn-success" href="{% url 'users:login' %}">Accedi</a>
            <a class="btn btn-primary" href="{% url 'users:register' %}">Registrati</a>
        </div>
    {% endif %}




    {% include 'footer.html' %}

    <script src="{% static 'js/listRecipes.js' %}"></script>
{% endblock %}