project/pages/urls.py
from django.urls import path, include
from . import views

app_name = 'pages'

urlpatterns = [
    path('', views.home_page, name='home_page'),
]

project/project/urls.py
from django.conf.urls.static import static
from django.conf import settings
import os

from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pages.urls', namespace='pages')),
    path('recipe/', include('recipe.urls', namespace='recipe')),
    path('users/', include('users.urls', namespace='user')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
else:
    from django.views.static import serve
    from django.urls import re_path

    urlpatterns += [
        re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    ]

project/recipe/urls.py
from django.urls import path
from .views import *

app_name = 'recipe'

urlpatterns = [
    path('createRecipe/', RecipeCreateView.as_view(), name='create_recipe'),
    path('createIngredient/', IngredientCreateView.as_view(), name='create_ingredient'),
    path('createBulkIngredient/', BulkIngredientCreateView.as_view(), name='create_bulk_ingredient'),
    path('deleteRecipe/<int:pk>/', RecipeDeleteView.as_view(), name='delete_recipe'),
    path('updateRecipe/<int:pk>/', RecipeUpdateView.as_view(), name='update_recipe'),
    path('listIngredients/', IngredientListView.as_view(), name='list_ingredients'),
    path('updateIngredient/<int:pk>/', update_ingredient, name='update_ingredient'),
    path('deleteIngredient/<int:pk>/', delete_ingredient, name='delete_ingredient'),
    path('createCategory/', CategoryCreateView.as_view(), name='create_category'),
    path('listCategories/', CategoryListView.as_view(), name='list_categories'),
    path('updateCategory/<int:pk>/', update_category, name='update_category'),
    path('deleteCategory/<int:pk>/', delete_category, name='delete_category'),
    path('detailRecipe/<int:pk>/', RecipeDetailView.as_view(), name='detail_recipe'),

]

project/recipe/forms.py
from django import forms
from .models import *
from django.forms import inlineformset_factory
from django.forms import BaseInlineFormSet


class recipeForm(forms.ModelForm):
    name = forms.CharField(
        label='Titolo',
        required=True,
        max_length=255,
        widget=forms.TextInput(attrs={'class': 'form-control'})
    )
    preparation = forms.CharField(
        label='Preparazione',
        widget=forms.Textarea(attrs={'class': 'form-control', 'placeholder':'step 1: ... \nstep 2: ...'})
    )
    category = forms.ModelChoiceField(
        label='Categoria',
        required=True,
        queryset=Category.objects.all(),
        widget=forms.Select(attrs={'class': 'form-control'})
    )
    difficult = forms.ChoiceField(
        label='Difficoltà',
        required=True,
        choices=Recipe.DIFFICULTIES,
        widget=forms.Select(attrs={'class': 'form-control'})
    )

    time_preparation = forms.IntegerField(
        label='Tempo di preparazione (minuti)',
        required=True,
        widget=forms.NumberInput(attrs={'class': 'form-control'})
    )

    cooking = forms.IntegerField(
        label='Tempo di cottura (minuti) / Tempo di riposo (minuti)',
        required=True,
        widget=forms.NumberInput(attrs={'class': 'form-control'})
    )

    servings = forms.IntegerField(
        label='Dosi',
        required=True,
        widget=forms.NumberInput(attrs={'class': 'form-control'})
    )

    cost = forms.ChoiceField(
        label='Costo',
        required=True,
        choices=Recipe.COSTS,
        widget=forms.Select(attrs={'class': 'form-control'})
    )

    image = forms.ImageField(
        label='Immagine',
        widget=forms.FileInput(attrs={'class': 'form-control'})
    )

    class Meta:
        model = Recipe
        fields = ['name', 'category', 'difficult', 'preparation', 'cooking', 'servings', 'cost', 'image', 'time_preparation']


class recipeIngredientForm(forms.ModelForm):
    ingredient = forms.ModelChoiceField(
        label='Ingrediente',
        required=True,
        queryset=Ingredient.objects.all(),
        widget=forms.Select(attrs={'class': 'form-control'})
    )
    quantity = forms.CharField(
        label='Quantità',
        required=True,
        max_length=10,
        widget=forms.TextInput(attrs={'class': 'form-control'})
    )
    unit_of_measure = forms.ChoiceField(
        label='Unità di misura',
        required=True,
        choices=RecipeIngredient.UNIT,
        widget=forms.Select(attrs={'class': 'form-control'})
    )

    class Meta:
        model = RecipeIngredient
        fields = ['ingredient', 'quantity', 'unit_of_measure']

    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user', None)  # Ottieni l'utente dai kwargs
        super().__init__(*args, **kwargs)
        if user:
            self.fields['ingredient'].queryset = Ingredient.objects.filter(user=user).order_by('name')


class ingredientForm(forms.ModelForm):
    name = forms.CharField(
        label='Nome',
        required=True,
        max_length=255,
        widget=forms.TextInput(attrs={'class': 'form-control'})
    )

    class Meta:
        model = Ingredient
        fields = ['name']

class categoryForm(forms.ModelForm):
    name = forms.CharField(
        label='Nome',
        required=True,
        max_length=255,
        widget=forms.TextInput(attrs={'class': 'form-control'})
    )

    class Meta:
        model = Category
        fields = ['name']

class noteForm(forms.ModelForm):
    text = forms.CharField(
        label='Note',
        required=False,
        widget=forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Note sulle ricetta'})
    )

    class Meta:
        model = Note
        fields = ['text']

class BaseRecipeIngredientFormSet(BaseInlineFormSet):
    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user', None)
        super().__init__(*args, **kwargs)
        for form in self.forms:
            form.user = self.user
            form.fields['ingredient'].queryset = Ingredient.objects.filter(user=self.user).order_by('name')


RecipeIngredientFormSet = inlineformset_factory(
    Recipe,
    RecipeIngredient,
    form=recipeIngredientForm,
    formset=BaseRecipeIngredientFormSet,
    extra=1,
    can_delete=True,
)

class bulkIngredientForm(forms.Form):
    ingredients = forms.CharField(
        label='Inserisci gli ingredienti (uno per riga)',
        widget=forms.Textarea(attrs={
            'class': 'form-control',
            'placeholder': 'Esempio:\nFarina\nZucchero\nUova\nLatte',
            'rows': 10,
        })
    )

project/recipe/views.py
import json

from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import JsonResponse
from django.shortcuts import redirect
from django.urls import reverse_lazy, reverse
from django.views.generic.edit import FormMixin
from django.views.generic import CreateView, ListView, DeleteView, DetailView, UpdateView, FormView

from .models import *
from .forms import *


class RecipeCreateView(LoginRequiredMixin, CreateView):
    model = Recipe
    form_class = recipeForm
    template_name = 'recipe/createRecipe.html'
    success_url = reverse_lazy('pages:home_page')

    login_url = 'users:login'

    def get_form(self, form_class=None):
        form = super().get_form(form_class)
        form.fields['category'].queryset = Category.objects.filter(user=self.request.user).order_by('name')

        return form

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.request.POST:
            context['ingredient_formset'] = RecipeIngredientFormSet(self.request.POST, user=self.request.user)
        else:
            context['ingredient_formset'] = RecipeIngredientFormSet(user=self.request.user)
        return context

    def form_valid(self, form):
        context = self.get_context_data()
        ingredient_formset = context['ingredient_formset']
        form.instance.user = self.request.user

        if ingredient_formset.is_valid():
            self.object = form.save()  # Salva la ricetta
            ingredient_formset.instance = self.object  # Associa gli ingredienti alla ricetta
            ingredient_formset.save()  # Salva il formset
            Note.objects.create(recipe=self.object)  # Crea una nota vuota per la ricetta
            return redirect(self.success_url)
        else:
            # Se il formset non è valido, ritorna il form con gli errori
            return self.render_to_response(self.get_context_data(form=form))


class IngredientCreateView(LoginRequiredMixin, CreateView):
    model = Ingredient
    form_class = ingredientForm
    template_name = 'recipe/createIngredient.html'

    login_url = 'users:login'

    def get_success_url(self):
        return reverse('pages:home_page')

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

class CategoryCreateView(LoginRequiredMixin, CreateView):
    model = Category
    form_class = categoryForm
    template_name = 'recipe/createCategory.html'

    login_url = 'users:login'

    def get_success_url(self):
        return reverse('pages:home_page')

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

class BulkIngredientCreateView(LoginRequiredMixin, FormView):
    model = Ingredient
    form_class = bulkIngredientForm
    template_name = 'recipe/createBulkIngredient.html'
    success_url = reverse_lazy('pages:home_page')

    login_url = 'users:login'

    def form_valid(self, form):
        ingredients = form.cleaned_data['ingredients'].split('\n')
        for ingredient in ingredients:
            ingredient = ingredient.capitalize().strip()
            Ingredient.objects.get_or_create(name=ingredient, user=self.request.user)

        return super().form_valid(form)


class RecipeDeleteView(LoginRequiredMixin, DeleteView):
    model = Recipe
    template_name = 'recipe/deleteRecipe.html'
    success_url = reverse_lazy('pages:home_page')

    login_url = 'users:login'

class RecipeUpdateView(LoginRequiredMixin, UpdateView):
    model = Recipe
    form_class = recipeForm
    template_name = 'recipe/updateRecipe.html'
    success_url = reverse_lazy('pages:home_page')

    login_url = 'users:login'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.request.POST:
            context['ingredient_formset'] = RecipeIngredientFormSet(self.request.POST, instance=self.object, user=self.request.user)
        else:
            context['ingredient_formset'] = RecipeIngredientFormSet(instance=self.object, user=self.request.user)
        return context

    def form_valid(self, form):
        context = self.get_context_data()
        ingredient_formset = context['ingredient_formset']

        if ingredient_formset.is_valid():
            self.object = form.save()  # Salva la ricetta
            ingredient_formset.instance = self.object  # Associa gli ingredienti alla ricetta
            ingredient_formset.save()  # Salva il formset
            return redirect(self.success_url)
        else:
            return self.render_to_response(self.get_context_data(form=form))


class IngredientListView(LoginRequiredMixin, ListView):
    model = Ingredient
    template_name = 'recipe/ingredientList.html'

    login_url = 'users:login'

    def get_queryset(self):
        return Ingredient.objects.filter(user=self.request.user).order_by('name')


def update_ingredient(request, pk):
    if request.method == 'POST':
        data = json.loads(request.body)
        try:
            ingredient = Ingredient.objects.get(pk=pk)
            ingredient.name = data['name']
            ingredient.save()
            return JsonResponse({'success': True})
        except Ingredient.DoesNotExist:
            return JsonResponse({'success': False, 'error': 'Ingredient not found'})
    return JsonResponse({'success': False, 'error': 'Invalid request method'})


def delete_ingredient(request, pk):
    if request.method == 'POST':
        try:
            ingredient = Ingredient.objects.get(pk=pk)
            ingredient.delete()
            return JsonResponse({'success': True})
        except Ingredient.DoesNotExist:
            return JsonResponse({'success': False, 'error': 'Ingredient not found'})
    return JsonResponse({'success': False, 'error': 'Invalid request method'})


class CategoryListView(LoginRequiredMixin, ListView):
    model = Category
    template_name = 'recipe/categoryList.html'

    def get_queryset(self):
        return Category.objects.filter(user=self.request.user).order_by('name')


def update_category(request, pk):
    if request.method == 'POST':
        data = json.loads(request.body)
        try:
            category = Category.objects.get(pk=pk)
            category.name = data['name']
            category.save()
            return JsonResponse({'success': True})
        except Ingredient.DoesNotExist:
            return JsonResponse({'success': False, 'error': 'Category not found'})
    return JsonResponse({'success': False, 'error': 'Invalid request method'})


def delete_category(request, pk):
    if request.method == 'POST':
        try:
            category = Category.objects.get(pk=pk)
            category.delete()
            return JsonResponse({'success': True})
        except Ingredient.DoesNotExist:
            return JsonResponse({'success': False, 'error': 'Category not found'})
    return JsonResponse({'success': False, 'error': 'Invalid request method'})


class RecipeDetailView(LoginRequiredMixin, FormMixin, DetailView):
    model = Recipe
    template_name = 'recipe/recipeDetail.html'
    form_class = noteForm

    login_url = 'users:login'

    # Per ritornare alla stessa pagina dopo il salvataggio
    def get_success_url(self):
        return reverse('recipe:detail_recipe', kwargs={'pk': self.object.pk})

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['ingredients'] = RecipeIngredient.objects.filter(recipe=self.object)
        # Ottieni (o crea) la nota associata alla ricetta
        note_instance, created = Note.objects.get_or_create(recipe=self.object)
        context['form'] = self.form_class(instance=note_instance)
        return context

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()  # Recupera l'oggetto Recipe
        # Ottieni (o crea) la nota associata alla ricetta
        note_instance, created = Note.objects.get_or_create(recipe=self.object)
        # Inizializza il form passando anche l'istanza esistente
        form = self.form_class(request.POST, instance=note_instance)

        if form.is_valid():
            note = form.save(commit=False)
            note.recipe = self.object
            note.save()
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

project/recipe/templates/recipe/categoryList.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Lista categorie{% endblock %}

{% block content %}
    {% include 'head.html' %}

    <div class="container">
        <h1>Lista di categorie</h1>
        {% for i in object_list %}
            <div class="card my-2 category-card" data-id="{{ i.id }}">
                <div class="card-body d-flex justify-content-between align-items-center">
                    <div>
                        <h5 class="card-title category-name">{{ i.name }}</h5>
                        <input type="text" class="form-control category-edit" value="{{ i }}" style="display: none;">
                    </div>
                    <button class="btn btn-danger btn-sm delete-category">
                        <i class="fas fa-trash-alt"></i>
                    </button>
                </div>
            </div>
        {% endfor %}
    </div>

    {% include 'footer.html' %}

    <script src="{% static 'js/modifyCategory.js' %}"></script>
{% endblock %}

project/recipe/templates/recipe/createBulkIngredient.html
{% extends 'base.html' %}

{% block title %}Create Many Ingredients{% endblock %}

{% block content %}
    {% include 'head.html' %}
    <div class="container mt-4">
        <h1>Crea tanti ingredienti</h1>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}

            <button type="submit" class="btn btn-primary">Salva</button>
        </form>
    </div>
    {% include 'footer.html' %}
{% endblock %}

project/recipe/templates/recipe/createCategory.html
{% extends 'base.html' %}

{% block title %}Create Category{% endblock %}

{% block content %}
    {% include 'head.html' %}
    <div class="container mt-4">
        <h1>Crea Categoria</h1>

        <form method="post">
            {% csrf_token %}

            <p>Dettagli della categoria</p>
            {{ form.as_p }}

            <button type="submit" class="btn btn-primary">Salva</button>
        </form>
    </div>
    {% include 'footer.html' %}
{% endblock %}

project/recipe/templates/recipe/createIngredient.html
{% extends 'base.html' %}

{% block title %}Create Ingredient{% endblock %}

{% block content %}
    {% include 'head.html' %}
    <div class="container mt-4">
        <div class="description w-100 d-flex justify-content-between align-items-center p-2">
            <h1>Crea Ingrediente</h1>
            <a href="{% url 'recipe:create_bulk_ingredient' %}" class="btn btn-primary">Crea ingredienti</a>
        </div>

        <form method="post">
            {% csrf_token %}

            <p>Dettagli dell'Ingrediente</p>
            {{ form.as_p }}

            <button type="submit" class="btn btn-primary">Salva</button>
        </form>
    </div>
    {% include 'footer.html' %}
{% endblock %}

project/recipe/templates/recipe/createRecipe.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Create Recipe{% endblock %}

{% block head %}
    <link rel="stylesheet" href="{% static 'css/createRecipe.css' %}">
{% endblock %}

{% block content %}
    {% include 'head.html' %}
    <div class="container mt-4">
        <h1>Crea Ricetta</h1>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}

            <h3>Dettagli della Ricetta</h3>
            <div class="mb-3">
                {{ form.name.label_tag }}
                {{ form.name }}
            </div>
            <div class="mb-3">
                {{ form.category.label_tag }}
                {{ form.category }}
            </div>
            <div class="mb-3">
                {{ form.image.label_tag }}
                {{ form.image }}
            </div>
            <div class="row mb-3">
                <div class="col-md-6">
                    {{ form.difficult.label_tag }}
                    {{ form.difficult }}
                </div>
                <div class="col-md-6">
                    {{ form.cost.label_tag }}
                    {{ form.cost }}
                </div>
            </div>
            <div class="row mb-3">
                <div class="col-md-4">
                    {{ form.time_preparation.label_tag }}
                    {{ form.time_preparation }}
                </div>
                <div class="col-md-4">
                    {{ form.cooking.label_tag }}
                    {{ form.cooking }}
                </div>
                <div class="col-md-4">
                    {{ form.servings.label_tag }}
                    {{ form.servings }}
                </div>
            </div>
            <div class="mb-3">
                {{ form.preparation.label_tag }}
                {{ form.preparation }}
            </div>

            <h3>Ingredienti</h3>
            <div id="formset-container">
                {{ ingredient_formset.management_form }}
                {% for form in ingredient_formset %}
                    <div class="formset-item">
                        {{ form.as_p }}
                        {% if not forloop.first %}
                            <button type="button" class="remove-ingredient btn btn-danger my-2">-</button>
                        {% endif %}
                    </div>
                {% endfor %}
            </div>

            <!-- Blocco nascosto per il template dell'empty_form -->
            <div id="empty-form" style="display: none;">
                <div class="formset-item">
                    {{ ingredient_formset.empty_form.as_p }}
                    <!-- Nel template dell'empty_form lasciamo il bottone; verrà nascosto se il nuovo form diventa il primo -->
                    <button type="button" class="remove-ingredient btn btn-danger my-2">-</button>
                </div>
            </div>

            <button type="button" class="btn btn-success" id="add-ingredient">+</button>
            <button type="submit" class="btn btn-primary">Salva</button>
        </form>
    </div>
    {% include 'footer.html' %}

    <script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
    <script src="{% static 'js/addIngredient.js' %}"></script>
{% endblock %}

project/recipe/templates/recipe/deleteRecipe.html
{% extends 'base.html' %}

{% block title %}Delete recipe{% endblock %}

{% block content %}
    {% include 'head.html' %}

    <div class="container mt-5">
        <h2>Riepilogo</h2>
        <div class="card">
            <div class="card-body">
                <h5 class="card-title">{{ recipe.name }}</h5>
                <img src="{{ recipe.image.url }}" class="img-fluid rounded-start" alt="img" style="height: 100px; width: 100px;">
                <p class="card-text">Categoria: {{ recipe.category }}</p>
                <p class="card-text">Preparazione: {{ recipe.preparation }}</p>
            </div>
        </div>

        <div class="mt-3">
            <form method="post">
                {% csrf_token %}
                <button type="submit" class="btn btn-danger">Si elimina</button>
                <a href="{% url 'pages:home_page' %}" class="btn btn-secondary">Torna indietro</a>
            </form>
        </div>
    </div>

    {% include 'footer.html' %}
{% endblock %}

project/recipe/templates/recipe/ingredientList.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Lista ingredienti{% endblock %}

{% block content %}
    {% include 'head.html' %}

    <div class="container">
        <h1>Lista di ingredienti</h1>
        {% for i in object_list %}
            <div class="card my-2 ingredient-card" data-id="{{ i.id }}">
                <div class="card-body d-flex justify-content-between align-items-center">
                    <div>
                        <h5 class="card-title ingredient-name">{{ i.name }}</h5>
                        <input type="text" class="form-control ingredient-edit" value="{{ i }}" style="display: none;">
                    </div>
                    <button class="btn btn-danger btn-sm delete-ingredient">
                        <i class="fas fa-trash-alt"></i>
                    </button>
                </div>
            </div>
        {% endfor %}
    </div>

    {% include 'footer.html' %}

    <script src="{% static 'js/modifyIngredient.js' %}"></script>
{% endblock %}

project/recipe/templates/recipe/recipeDetail.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Dettagli ricetta{% endblock %}

{% block head %}
    <link rel="stylesheet" href="{% static 'css/recipeDetail.css' %}">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.min.js"></script>
{% endblock %}

{% block content %}
    {% include 'head.html' %}

    <div class="container my-2 recipe-detail">
        <h1>{{ object.name }}</h1>
        <div class="row border border-1 rounded p-3">
            <div class="col-md-6 me-4">
                <img src="{{ object.image.url }}" alt="{{ object.name }}" class="detail-img-fluid detail-img-container mb-3">
            </div>
            <div class="col-md-1 border-end"></div>
            <div class="col-md-4 d-flex flex-column align-items-start ms-4">
                <p><i class="fa fa-graduation-cap recipe-symbols" aria-hidden="true"></i> Difficolta: <strong>{{ object.difficult }}</strong></p>
                <p><i class="fa fa-spoon recipe-symbols" aria-hidden="true"></i> Preparazione: <strong>{{ object.time_preparation }} min</strong></p>
                <p><i class="fa fa-clock recipe-symbols" aria-hidden="true"></i> Tempo di cottura/riposo <strong>{{ object.cooking }} min</strong></p>
                <p><i class="fa fa-users recipe-symbols" aria-hidden="true"></i> Dosi: <strong>{{ object.servings }}</strong></p>
                <p><i class="fa fa-eur recipe-symbols"></i> Costo: <strong>{{ object.cost }}</strong></p>
            </div>
        </div>
        <div class="bg-light p-3 mt-3" style="font-family: 'Verdana', sans-serif;">
            <h3>Ingredienti</h3>
            <ul>
                {% for i in object.ingredients.all %}
                    <li>{{ i.ingredient.name }}:
                        {% if i.unit_of_measure != 'qb' %}
                            {{ i.quantity }}
                        {% endif %}
                        {{ i.unit_of_measure }}</li>
                {% endfor %}
            </ul>
        </div>
        <div class="mt-3">
            <h3>Procedimento</h3>
            <p>{{ object.preparation }}</p>
        </div>
        <hr>
        <!-- Note section -->
        <div class="mt-4">
            <h3>Note</h3>
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-primary">Salva</button>
            </form>
        </div>
    </div>

    {% include 'footer.html' %}
{% endblock %}

project/recipe/templates/recipe/updateRecipe.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Create Recipe{% endblock %}

{% block head %}
    <link rel="stylesheet" href="{% static 'css/createRecipe.css' %}">
{% endblock %}

{% block content %}
    {% include 'head.html' %}
    <div class="container mt-4">
        <h1>Modifica Ricetta</h1>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}

            <h3>Dettagli della Ricetta</h3>
            <div class="mb-3">
                {{ form.name.label_tag }}
                {{ form.name }}
            </div>
            <div class="mb-3">
                {{ form.category.label_tag }}
                {{ form.category }}
            </div>
            <div class="mb-3">
                {{ form.image.label_tag }}
                {{ form.image }}
            </div>
            <div class="row mb-3">
                <div class="col-md-6">
                    {{ form.difficult.label_tag }}
                    {{ form.difficult }}
                </div>
                <div class="col-md-6">
                    {{ form.cost.label_tag }}
                    {{ form.cost }}
                </div>
            </div>
            <div class="row mb-3">
                <div class="col-md-4">
                    {{ form.time_preparation.label_tag }}
                    {{ form.time_preparation }}
                </div>
                <div class="col-md-4">
                    {{ form.cooking.label_tag }}
                    {{ form.cooking }}
                </div>
                <div class="col-md-4">
                    {{ form.servings.label_tag }}
                    {{ form.servings }}
                </div>
            </div>
            <div class="mb-3">
                {{ form.preparation.label_tag }}
                {{ form.preparation }}
            </div>

            <h3>Ingredienti</h3>
            <div id="formset-container">
                {{ ingredient_formset.management_form }}
                {% for form in ingredient_formset %}
                    <div class="formset-item">
                        {{ form.as_p }}
                        {% if not forloop.first %}
                            <button type="button" class="remove-ingredient btn btn-danger my-2">-</button>
                        {% endif %}
                    </div>
                {% endfor %}
            </div>

            <!-- Blocco nascosto per il template dell'empty_form -->
            <div id="empty-form" style="display: none;">
                <div class="formset-item">
                    {{ ingredient_formset.empty_form.as_p }}
                    <!-- Nel template dell'empty_form lasciamo il bottone; verrà nascosto se il nuovo form diventa il primo -->
                    <button type="button" class="remove-ingredient btn btn-danger my-2">-</button>
                </div>
            </div>

            <button type="button" class="btn btn-success" id="add-ingredient">+</button>
            <button type="submit" class="btn btn-primary">Salva</button>
        </form>
    </div>
    {% include 'footer.html' %}

    <script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
    <script src="{% static 'js/addIngredient.js' %}"></script>
{% endblock %}
